apiVersion: v1
kind: Pod
metadata:
  name: dogs
  namespace: dogns
  labels:
    run: dogs
    app: dogs
spec:
  containers:
  - name: dogs
    image: 946401916599.dkr.ecr.us-east-1.amazonaws.com/dogs:dog-image
    ports:
    - containerPort: 80
      protocol: TCP
  dnsPolicy: ClusterFirst
  restartPolicy: Always