---
apiVersion: v1
kind: Service
metadata:
  name: cats
  labels:
    run: cats
    app: cats
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    run: cats
    app: cats
        